spring.application.name=tienda-fgg-web
#server.servlet.context-path=/tienda-fgg

# H2
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true