INSERT INTO categorias
    (nombre, descripcion, imagen) VALUES
        ('Aventura', 'Explora mundos épicos', 'aventura.jpg'),
        ('Shooter', 'Acción frenética en primera persona', 'shooter.png'),
        ('Estrategia', 'Explora mundos épicos', 'estrategia.png'),
        ('RPG', 'Acción frenética en primera persona', 'rpg.png');

INSERT INTO videojuegos
(codigo_ean, titulo, marca, descripcion, precio, descuento, categoria_id, imagen)
VALUES
    ('8431000000001', 'The Legend of Zelda: Breath of the Wild', 'Nintendo', 'Explora un vasto mundo abierto lleno de secretos, templos y desafíos donde cada rincón invita a la aventura. Combina exploración, combate y resolución de puzles con total libertad en una experiencia inmersiva y dinámica.', 59.99, 0, 1, 'botw.jpg'),
    ('8431000000002', 'Uncharted 4: A Thief''s End', 'Naughty Dog', 'Acompaña a Nathan Drake en una aventura cinematográfica repleta de acción, misterios y tesoros ocultos. Viaja por escenarios espectaculares mientras enfrentas peligros y descubres una historia emocionante llena de giros.', 19.99, 10, 1, 'uncharted4.jpg'),
    ('8431000000003', 'Life is Strange', 'Dontnod Entertainment', 'Sumérgete en una historia emocional donde tus decisiones alteran el tiempo y el destino. Vive una narrativa profunda con personajes complejos mientras exploras temas como la amistad, el sacrificio y las consecuencias.', 19.04, 20, 1, 'LifeStrange.jpg'),
    ('8431000000004', 'Red Dead Redemption 2', 'Rockstar Games', 'Viaja por un mundo abierto detallado en el Salvaje Oeste, donde cada decisión afecta tu historia. Disfruta de una narrativa madura, misiones variadas y un entorno vivo que reacciona a tus acciones.', 39.99, 10, 1, 'rdr2.jpg'),
    ('8431000000005', 'Monkey Island 2: LeChuck''s Revenge', 'LucasArts', 'Embárcate en una aventura clásica de piratas con humor ingenioso y desafiantes acertijos. Explora islas, interactúa con personajes únicos y descubre una historia llena de encanto y situaciones absurdas.', 9.99, 0, 1, 'monkeyisland2.jpg'),
    ('8431000000006', 'Tomb Raider (2013)', 'Crystal Dynamics', 'Descubre el origen de Lara Croft en una isla hostil llena de misterios y peligros. Combina exploración, supervivencia y combate en una aventura intensa que muestra la evolución de la protagonista.', 14.99, 30, 1, 'tombraider.jpg'),
    ('8431000000007', 'The Last of Us Part I', 'Naughty Dog', 'Vive una historia postapocalíptica cargada de emociones mientras acompañas a Joel y Ellie. Combina sigilo, combate y narrativa profunda en un viaje marcado por la supervivencia y los vínculos humanos.', 19.99, 40, 1, 'tlou.jpg'),
    ('8431000000008', 'Horizon Zero Dawn', 'Guerrilla Games', 'Explora un mundo dominado por máquinas en esta aventura de acción y rol. Descubre secretos del pasado mientras cazas criaturas mecánicas y desarrollas habilidades en un entorno abierto espectacular.', 29.99, 0, 1, 'horizonzero.jpg'),
    ('8431000000009', 'The Walking Dead: Season One', 'Telltale Games', 'Vive un drama interactivo en un mundo devastado por zombis donde cada decisión importa. Construye relaciones, enfrenta dilemas morales y experimenta una historia intensa que cambia según tus elecciones.', 19.99, 10, 1, 'twd1.png'),

    ('8431000000010', 'DOOM Eternal', 'id Software', 'Combate hordas de demonios en un shooter frenético lleno de acción y velocidad. Utiliza un arsenal devastador mientras te mueves constantemente en escenarios dinámicos llenos de desafíos.', 19.99, 20, 2, 'doometernal.jpg'),
    ('8431000000011', 'Call of Duty: Advanced Warfare', 'Sledgehammer Games', 'Sumérgete en combates futuristas con tecnología avanzada y acción intensa. Disfruta de una campaña dinámica y modos multijugador competitivos con gran variedad de armas y habilidades.', 9.38, 20, 2, 'cod.jpg'),
    ('8431000000012', 'Battlefield 1', 'DICE', 'Experimenta la guerra a gran escala en escenarios inspirados en la Primera Guerra Mundial. Participa en batallas masivas con vehículos, destrucción dinámica y combates realistas.', 13.00, 40, 2, 'battlefield1.jpg'),
    ('8431000000013', 'Tom Clancy''s Rainbow Six Siege', 'Ubisoft Montreal', 'Shooter táctico donde la coordinación y estrategia son clave. Forma equipo, planifica ataques y aprovecha la destrucción del entorno para superar a tus rivales en partidas intensas.', 24.50, 60, 2, 'rss.webp'),
    ('8431000000014', 'PAYDAY 3', 'Starbreeze Studios', 'Realiza atracos cooperativos donde la planificación y el trabajo en equipo marcan la diferencia. Ejecuta golpes perfectos mientras gestionas recursos y enfrentas situaciones imprevisibles.', 9.06, 50, 2, 'payday3.jpg'),
    ('8431000000015', 'High on Life', 'Squanch Games', 'Disfruta de un shooter único con humor irreverente y armas parlantes. Explora un universo alienígena lleno de situaciones absurdas y combate enemigos en escenarios coloridos.', 39.99, 10, 2, 'highonlife.jpg'),
    ('8431000000016', 'Gears of War: Ultimate Edition', 'The Coalition', 'Lucha contra hordas alienígenas en un intenso shooter en tercera persona basado en coberturas. Vive una historia épica con combates tácticos y acción constante.', 19.99, 0, 2, 'gears.jpg'),

    ('8431000000017', 'Sid Meier''s Civilization VI', 'Firaxis Games', 'Desarrolla una civilización desde sus inicios hasta la era moderna en este juego de estrategia por turnos. Gestiona recursos, diplomacia y guerras mientras expandes tu imperio.', 3.62, 20, 3, 'civilizationvi.jpg'),
    ('8431000000018', 'Age of Empires IV', 'Relic Entertainment', 'Construye imperios históricos y lidera ejércitos en batallas estratégicas en tiempo real. Gestiona economía, tecnología y expansión en diferentes civilizaciones.', 19.97, 0, 3, 'ageiv.png'),
    ('8431000000019', 'Panzer Corps 2', 'Flashback Games', 'Dirige ejércitos en campañas estratégicas basadas en conflictos históricos. Planifica movimientos, gestiona unidades y toma decisiones tácticas para lograr la victoria.', 1.12, 0, 3, 'panzercorps.jpg'),
    ('8431000000020', 'Crusader Kings III', 'Paradox Development Studio', 'Gestiona una dinastía medieval tomando decisiones políticas, militares y personales. Construye alianzas, conquista territorios y asegura la supervivencia de tu linaje.', 29.99, 40, 3, 'ckiii.jpg'),
    ('8431000000021', 'Command & Conquer Remastered Collection', 'Petroglyph Games', 'Revive un clásico de estrategia en tiempo real con gráficos renovados. Gestiona bases, recolecta recursos y lidera ejércitos en intensas batallas tácticas.', 7.95, 30, 3, 'cac.jpg'),

    ('8431000000022', 'The Witcher 3: Wild Hunt', 'CD Projekt Red', 'Explora un mundo abierto lleno de decisiones morales y criaturas fantásticas. Vive una historia profunda mientras completas misiones, combates enemigos y desarrollas habilidades.', 9.99, 30, 4, 'witcheriii.jpg'),
    ('8431000000023', 'The Elder Scrolls V: Skyrim', 'Bethesda Game Studios', 'Adéntrate en un vasto mundo de fantasía donde puedes forjar tu propio destino. Completa misiones, desarrolla habilidades y explora libremente un entorno lleno de secretos.', 19.99, 40, 4, 'skyrim.jpg'),
    ('8431000000024', 'Cyberpunk 2077', 'CD Projekt Red', 'Sumérgete en una ciudad futurista llena de vida, decisiones y peligros. Personaliza tu personaje y elige tu camino en una historia donde cada elección tiene consecuencias.', 39.99, 50, 4, 'cyberpunk.jpg'),
    ('8431000000025', 'Dark Souls III', 'FromSoftware', 'Enfréntate a desafiantes enemigos en un mundo oscuro y atmosférico. Domina el combate táctico mientras exploras entornos llenos de secretos y peligros constantes.', 29.99, 0, 4, 'dsiii.jpg'),
    ('8431000000026', 'Persona 5 Royal', 'Atlus', 'Combina vida estudiantil con combates por turnos en mundos cognitivos. Desarrolla relaciones y enfrenta enemigos mientras descubres una historia profunda y estilizada.', 29.99, 0, 4, 'p5r.webp'),
    ('8431000000027', 'Dragon Age: Inquisition', 'BioWare', 'Lidera una organización destinada a salvar el mundo en un RPG lleno de decisiones. Forma alianzas, combate enemigos y explora un mundo rico en historia.', 19.99, 20, 4, 'dai.png'),
    ('8431000000028', 'Clair Obscur: Expedition 33', 'Sandfall Interactive', 'Explora un mundo inspirado en la Belle Époque con combates por turnos y mecánicas dinámicas. Vive una historia artística con un sistema de combate innovador.', 49.99, 30, 4, 'expedition33.webp'),
    ('8431000000029', 'Fallout 4', 'Bethesda Game Studios', 'Sobrevive en un mundo postapocalíptico lleno de peligros y decisiones. Construye asentamientos, explora ruinas y define tu destino en un entorno abierto.', 19.99, 20, 4, 'fallout4.webp'),
    ('8431000000030', 'Kingdom Come: Deliverance', 'Warhorse Studios', 'Vive una experiencia realista en la Edad Media con combates exigentes y narrativa histórica. Toma decisiones que afectan tu reputación y desarrollo.', 7.99, 10, 4, 'kcd.jpg'),
    ('8431000000031', 'Octopath Traveler', 'Square Enix', 'Disfruta de un RPG clásico con estilo visual único y múltiples historias entrelazadas. Elige tu camino y descubre los destinos de ocho personajes distintos.', 23.99, 0, 4, 'octopathtraveller.jpg');